[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "youtube-dl>=2021.12.17",
    "yt-dlp>=2025.6.30",
]
